name: BetterPVP-Plugin
version: ${project.version}
main: me.sm.apvpplugin.ApvpPlugin
api-version: 1.16
authors:
  - modione
  - someron
commands:
  pvp:
    permission: apvp.setpvp

permissions:
  apvp.setpvp:
    default: op